CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE ARTICLE
(
    UUID       UUID default uuid_generate_v4() PRIMARY KEY,
    CREATED_AT TIMESTAMP    NOT NULL,
    CHANGED_AT TIMESTAMP    NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    TITLE      VARCHAR(100) NOT NULL,
    TEXT       TEXT         NOT NULL
);
